name: emp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - statsmodels
  - mne-base
  - h5io
  - h5py
  - pymatreader
  - pyprep
  - autoreject
  - ipython
  - ipykernel
  - pre-commit
  - black
  - isort
  - flake8
  - flake8-docstrings
  - click
  - psutil
  - pip:
    - datalad
