name: emp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - statsmodels
  - mne-base
  - mne_qt_browser
  - h5io
  - h5py
  - pymatreader
  - ipython
  - ipykernel
  - pre-commit
  - black
  - isort
  - flake8
  - flake8-docstrings
  - git-annex
  - pip:
    - datalad
